name: Exchange_Rate_API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Pull Docker image
      run: docker pull bgarbach/exchange_rate_api:0.1

    - name: Run tests on the Docker image
      run: docker run --env API_KEY=${{ secrets.API_KEY }} bgarbach/exchange_rate_api:0.1 cargo test

    #- uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --build-arg API_KEY=${{env.API_KEY}} --tag my-image-name:$(date +%s)
