name: Exchange_Rate_API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_rust_code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 1
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  build_docker_image:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: API_KEY
    steps:
    - name: Checkout 2
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: set up Docker buildx 
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push 
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/exchange_rate_api:latest